import { useEffect, useState, type FormEvent } from 'react';
import { Navigate, Link, useLocation, useNavigate } from 'react-router-dom';
import { CalendarDays, CircleDollarSign, HeartHandshake, LoaderCircle, ShieldCheck, UserRound } from 'lucide-react';
import axios from 'axios';
import { toast } from 'sonner';
import { useAuth } from '../context/AuthContext';
import { api } from '../lib/api';
import { fallbackEvents, type Donation } from '../data';
import { PageHeader } from '../components/Layout';

export function Protected({ admin = false, children }: { admin?: boolean; children: React.ReactNode }) {
  const { user, loading } = useAuth();
  if (loading) return <div className="grid min-h-[50vh] place-items-center"><LoaderCircle className="animate-spin text-kumkum" /></div>;
  if (!user) return <Navigate to="/login" replace />;
  if (admin && user.role === 'USER') return <Navigate to="/dashboard" replace />;
  return children;
}

export function Login() {
  const [registering, setRegistering] = useState(false); const [busy, setBusy] = useState(false);
  const { user, login, register } = useAuth(); const navigate = useNavigate(); const location = useLocation();
  if (user) return <Navigate to={user.role === 'USER' ? '/dashboard' : '/admin'} replace />;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const values = Object.fromEntries(new FormData(event.currentTarget)); try { if (registering) await register(values as Record<string, string>); else await login(String(values.email), String(values.password)); toast.success(registering ? 'Welcome to the community' : 'Welcome back'); navigate((location.state as { from?: string })?.from ?? '/dashboard'); } catch (error) { const message = axios.isAxiosError(error) ? (error.response?.data?.message ?? 'Cannot reach the server. Confirm the API is running.') : 'Please check your details and try again'; toast.error(message); } finally { setBusy(false); } }
  return <section className="container-page grid min-h-[70vh] place-items-center py-14"><div className="panel w-full max-w-md p-7"><span className="mx-auto grid size-14 place-items-center rounded-full bg-orange-100 text-kumkum"><UserRound /></span><h1 className="mt-4 text-center font-display text-3xl text-kumkum">{registering ? 'Join the Community' : 'Member Sign In'}</h1><form className="mt-7 space-y-4" onSubmit={submit}>{registering && <><input className="field" name="name" placeholder="Full name" required /><input className="field" name="mobile" placeholder="Mobile number" /></>}<input className="field" name="email" type="email" placeholder="Email address" required /><input className="field" name="password" type="password" minLength={8} placeholder="Password (minimum 8 characters)" required /><button className="btn-primary w-full" disabled={busy}>{busy && <LoaderCircle className="animate-spin" size={18} />}{registering ? 'Create account' : 'Sign in'}</button></form><button className="mt-5 w-full text-sm font-bold text-kumkum" onClick={() => setRegistering(!registering)}>{registering ? 'Already registered? Sign in' : 'New here? Create an account'}</button></div></section>;
}

function Status({ value }: { value: Donation['status'] }) { const styles = { PENDING: 'bg-yellow-100 text-yellow-800', VERIFIED: 'bg-green-100 text-green-800', REJECTED: 'bg-red-100 text-red-800' }; return <span className={`rounded px-2 py-1 text-xs font-bold ${styles[value]}`}>{value}</span>; }

export function Dashboard() {
  const { user } = useAuth(); const [donations, setDonations] = useState<Donation[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { api.get<Donation[]>('/donations/mine').then(({ data }) => setDonations(data)).catch(() => toast.error('Could not load donation history')).finally(() => setLoading(false)); }, []);
  return <><PageHeader eyebrow="Member dashboard" title={`Namaskar, ${user?.name ?? ''}`}><span className="inline-flex items-center gap-2"><ShieldCheck size={17} /> Your personal details and donation records are visible only to you.</span></PageHeader><section className="container-page py-12"><div className="grid gap-5 md:grid-cols-3"><Summary icon={<UserRound />} label="Account role" value={user?.role ?? 'USER'} /><Summary icon={<CalendarDays />} label="Next event" value={fallbackEvents[0].name} /><Summary icon={<CircleDollarSign />} label="Your donations" value={String(donations.length)} /></div><div className="mt-10 flex flex-wrap items-center justify-between gap-4"><h2 className="font-display text-3xl text-kumkum">Donation History</h2><Link className="btn-primary" to="/donate"><HeartHandshake size={18} /> New donation</Link></div><div className="panel mt-5 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-orange-50 text-cocoa/65"><tr><th className="p-4">Date</th><th>Purpose</th><th>Payment Method</th><th>Amount</th><th>Status</th></tr></thead><tbody>{loading ? <tr><td className="p-6" colSpan={5}>Loading records...</td></tr> : donations.length ? donations.map((donation) => <tr className="border-t border-cocoa/10" key={donation.id}><td className="p-4">{new Date(donation.createdAt).toLocaleDateString('en-IN')}</td><td>{donation.purpose}</td><td>{donation.paymentMethod}</td><td className="font-bold">₹{Number(donation.amount).toLocaleString('en-IN')}</td><td><Status value={donation.status} /></td></tr>) : <tr><td className="p-8 text-center text-cocoa/55" colSpan={5}>No donations submitted yet.</td></tr>}</tbody></table></div></section></>;
}
function Summary({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="panel flex items-center gap-4 p-5"><span className="grid size-11 place-items-center rounded bg-orange-100 text-kumkum">{icon}</span><div><p className="text-xs font-bold uppercase tracking-widest text-cocoa/50">{label}</p><p className="mt-1 font-bold">{value}</p></div></div>; }

export function Donate() {
  const { user } = useAuth(); const navigate = useNavigate(); const [busy, setBusy] = useState(false);
  const handleCopyPhone = () => { navigator.clipboard.writeText('1234567891'); toast.success('Phone number copied!'); };
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await api.post('/donations', { ...values, amount: Number(values.amount) }); toast.success('Donation submitted for verification'); navigate('/dashboard'); } catch (err: any) { console.error('Donation error:', err.response?.data || err.message); toast.error(err.response?.data?.message || 'Could not submit donation'); } finally { setBusy(false); } }
  return <><PageHeader eyebrow="Community contribution" title="Submit a Donation">Enter the details of your donation to support the celebration.</PageHeader><section className="container-page max-w-3xl py-12"><form className="panel grid gap-5 p-6 sm:grid-cols-2" onSubmit={submit}><label className="text-sm font-bold">Donor name<input className="field mt-2" name="donorName" defaultValue={user?.name} required /></label><label className="text-sm font-bold">Mobile<input className="field mt-2" name="mobile" defaultValue={user?.mobile} required /></label><label className="text-sm font-bold">Amount (₹)<input className="field mt-2" name="amount" type="number" min="1" step="0.01" required /></label><label className="text-sm font-bold">Purpose<select className="field mt-2" name="purpose"><option>General festival fund</option><option>Prasad seva</option><option>Decoration</option><option>Cultural programs</option></select></label><label className="text-sm font-bold">Payment method<select className="field mt-2" name="paymentMethod"><option>UPI</option><option>Cash</option></select></label><div className="rounded-lg border border-marigold/30 bg-marigold/5 p-4 sm:col-span-2"><p className="text-sm font-bold text-cocoa">📱 Send payment to:</p><p className="mt-2 text-lg font-bold text-kumkum">Manish Kumar</p><div className="mt-2 flex items-center gap-2"><p className="text-sm text-cocoa/70">Phone: 1234567891</p><button type="button" onClick={handleCopyPhone} className="rounded bg-kumkum/10 px-2 py-1 text-xs font-semibold text-kumkum hover:bg-kumkum/20">Copy</button></div></div><div className="sm:col-span-2"><p className="mb-4 text-sm text-cocoa/55">No payment is processed on this website. Submit only after making payment through a committee-approved method.</p><button className="btn-primary w-full sm:w-auto" disabled={busy}>{busy && <LoaderCircle className="animate-spin" size={18} />} Submit for verification</button></div></form></section></>;
}
export { Status };