import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { BellRing, CalendarDays, Clock3, HeartHandshake, MapPin, Sparkles, UsersRound, X } from 'lucide-react';
import { api } from '../lib/api';
import { fallbackAnnouncements, fallbackEvents, fallbackGallery, type Announcement, type FestivalEvent, type GalleryImage } from '../data';
import { PageHeader } from '../components/Layout';

function usePublicData<T>(path: string, fallback: T[]) {
  const [items, setItems] = useState(fallback);
  useEffect(() => { api.get<T[]>(`/public/${path}`).then(({ data }) => data.length && setItems(data)).catch(() => undefined); }, [path]);
  return items;
}

export function Home() {
  const events = usePublicData<FestivalEvent>('events', fallbackEvents);
  const [total, setTotal] = useState(0);
  useEffect(() => { api.get<{ totalVerified: number }>('/public/donations/total').then(({ data }) => setTotal(Number(data.totalVerified))).catch(() => undefined); }, []);
  return <>
    <section className="relative min-h-[78vh] overflow-hidden bg-cocoa text-white">
      <img className="absolute inset-0 h-full w-full object-cover opacity-45" src={fallbackGallery[0].imageUrl} alt="Pachhapur Ganesh Utsav celebration" />
      <div className="absolute inset-0 bg-gradient-to-r from-cocoa via-cocoa/75 to-transparent" />
      <div className="container-page relative flex min-h-[78vh] items-center py-20"><div className="max-w-3xl"><p className="mb-5 inline-flex items-center gap-2 border-l-4 border-marigold pl-3 text-sm font-bold uppercase tracking-widest text-marigold"><Sparkles size={17} /> Ganesh Utsav 2026</p><h1 className="font-display text-5xl leading-tight sm:text-7xl lg:text-8xl">Pachhapur<br /><span className="text-marigold">Ka Samrat</span></h1><p className="mt-6 max-w-xl text-lg text-white/80">Where faith brings a community together. Join us for eleven days of devotion, culture, music, and seva.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn-primary !bg-marigold !text-cocoa hover:!bg-yellow-400" to="/events"><CalendarDays size={19} /> Explore events</Link><Link className="btn-secondary !border-white/30 !bg-white/10 !text-white hover:!bg-white/20" to="/donate"><HeartHandshake size={19} /> Make a donation</Link></div></div></div>
    </section>
    <section className="bg-kumkum text-white"><div className="container-page grid divide-y divide-white/15 py-7 sm:grid-cols-3 sm:divide-x sm:divide-y-0"><Stat value="11 Days" label="of celebration" /><Stat value="48+ Years" label="of tradition" /><Stat value="One Family" label="our Pachhapur" /></div></section>
    <section className="container-page py-20"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Festival calendar</p><h2 className="mt-2 font-display text-4xl text-kumkum">Upcoming Celebrations</h2></div><Link className="font-bold text-kumkum" to="/events">View full schedule →</Link></div><div className="mt-9 grid gap-5 md:grid-cols-3">{events.slice(0, 3).map((event) => <EventCard key={event.id} event={event} />)}</div></section>
    <section className="bg-marigold py-16"><div className="container-page flex flex-col items-start justify-between gap-7 md:flex-row md:items-center"><div><p className="eyebrow !text-cocoa/60">Community seva</p><h2 className="mt-2 font-display text-4xl text-cocoa">Help us create a celebration for everyone.</h2><p className="mt-4 text-sm font-semibold text-cocoa/70">₹{total.toLocaleString('en-IN')} contributed so far</p></div><Link to="/donate" className="btn-primary shrink-0"><HeartHandshake size={20} /> Donate securely</Link></div></section>
  </>;
}
function Stat({ value, label }: { value: string; label: string }) { return <div className="px-6 py-4 text-center"><strong className="font-display text-3xl text-marigold">{value}</strong><span className="ml-2 text-sm text-white/70">{label}</span></div>; }
function EventCard({ event }: { event: FestivalEvent }) { return <article className="panel overflow-hidden"><div className="h-2 bg-gradient-to-r from-kumkum via-saffron to-marigold" /><div className="p-6"><time className="eyebrow">{new Date(event.date).toLocaleDateString('en-IN', { weekday: 'short', day: 'numeric', month: 'long' })}</time><h3 className="mt-3 text-xl font-bold">{event.name}</h3><p className="mt-3 text-sm text-cocoa/65">{event.description}</p><div className="mt-5 space-y-2 text-sm font-medium"><p className="flex gap-2"><Clock3 size={17} className="text-saffron" />{event.time}</p><p className="flex gap-2"><MapPin size={17} className="text-saffron" />{event.location}</p></div></div></article>; }

export function About() { return <><PageHeader eyebrow="Our legacy" title="Faith. Seva. Togetherness.">Pachhapur Ka Samrat is more than a festival. It is a shared tradition built by generations of local families.</PageHeader><section className="container-page grid items-center gap-12 py-16 md:grid-cols-2"><img className="aspect-[4/3] w-full rounded-lg object-cover shadow-ceremonial" src={fallbackGallery[2].imageUrl} alt="Community festival celebration" /><div><p className="eyebrow">Our story</p><h2 className="mt-2 font-display text-4xl text-kumkum">A celebration with purpose</h2><p className="mt-5 leading-7 text-cocoa/70">The mandal was formed to celebrate Shri Ganesh with dignity while creating a platform for cultural programs, youth participation, and meaningful community service.</p><div className="mt-8 grid grid-cols-2 gap-5"><Value icon={<UsersRound />} title="Community first" /><Value icon={<HeartHandshake />} title="Service always" /></div></div></section></>; }
function Value({ icon, title }: { icon: React.ReactNode; title: string }) { return <div className="border-l-4 border-marigold pl-4"><span className="text-kumkum">{icon}</span><strong className="mt-2 block">{title}</strong></div>; }

export function Events() { const events = usePublicData<FestivalEvent>('events', fallbackEvents); return <><PageHeader eyebrow="Festival schedule" title="Events & Ceremonies">Plan your darshan and join every special moment of the celebration.</PageHeader><section className="container-page grid gap-6 py-14 md:grid-cols-2 lg:grid-cols-3">{events.map((event) => <EventCard key={event.id} event={event} />)}</section></>; }

export function Announcements() { const items = usePublicData<Announcement>('announcements', fallbackAnnouncements); return <><PageHeader eyebrow="Stay informed" title="Announcements">Updates from the Pachhapur Ka Samrat Utsav committee.</PageHeader><section className="container-page max-w-4xl space-y-4 py-14">{items.map((item) => <article key={item.id} className={`panel flex gap-5 p-6 ${item.important ? 'border-l-4 !border-l-kumkum' : ''}`}><BellRing className="mt-1 shrink-0 text-saffron" /><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-bold">{item.title}</h2>{item.important && <span className="rounded bg-red-100 px-2 py-1 text-xs font-bold text-kumkum">IMPORTANT</span>}</div><p className="mt-2 text-cocoa/65">{item.content}</p></div></article>)}</section></>; }

export function Gallery() { const images = usePublicData<GalleryImage>('gallery', fallbackGallery); const [selected, setSelected] = useState<GalleryImage | null>(null); return <><PageHeader eyebrow="Festival memories" title="Gallery">Moments of devotion, joy, and community from our celebrations.</PageHeader><section className="container-page grid grid-cols-2 gap-3 py-12 md:grid-cols-3 md:gap-5">{images.map((image, index) => <button key={image.id} className={`group overflow-hidden rounded-md ${index % 5 === 0 ? 'md:col-span-2 md:row-span-2' : ''}`} onClick={() => setSelected(image)}><img className="aspect-square h-full w-full object-cover transition duration-500 group-hover:scale-105" src={image.imageUrl} alt={image.altText} /><span className="sr-only">View {image.title}</span></button>)}</section>{selected && <div className="fixed inset-0 z-50 grid place-items-center bg-black/90 p-4" role="dialog" aria-modal="true"><button className="absolute right-5 top-5 p-3 text-white" title="Close" onClick={() => setSelected(null)}><X /></button><figure><img className="max-h-[82vh] max-w-full rounded object-contain" src={selected.imageUrl} alt={selected.altText} /><figcaption className="mt-3 text-center text-white">{selected.title}</figcaption></figure></div>}</>; }

export function Contact() { return <><PageHeader eyebrow="Connect with us" title="Contact the Mandal">Questions about events, volunteering, or donations? Our committee is here to help.</PageHeader><section className="container-page grid gap-10 py-14 md:grid-cols-2"><div className="space-y-8"><div><MapPin className="text-saffron" /><h2 className="mt-2 text-xl font-bold">Festival Mandap</h2><p className="text-cocoa/65">Naduvin Pete Bazar Road, Pachhapur, Karnataka</p></div><div><h2 className="text-xl font-bold">Committee contact</h2><p className="mt-2 text-cocoa/65">+91 90000 00000<br />hello@pachhapurkasamrat.org</p></div></div><form className="panel space-y-4 p-6" onSubmit={(event) => event.preventDefault()}><h2 className="font-display text-2xl text-kumkum">Send a message</h2><input className="field" placeholder="Your name" required /><input className="field" type="email" placeholder="Email address" required /><textarea className="field min-h-32" placeholder="How can we help?" required /><button className="btn-primary" type="submit">Send message</button></form></section></>; }